# Generated by Django 4.2.6 on 2023-10-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fungi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fungi",
            name="comestible",
        ),
        migrations.AddField(
            model_name="fungi",
            name="edibility",
            field=models.CharField(
                choices=[("COM", "Comestible"), ("TOX", "Toxic"), ("MOR", "Mortal")],
                default="COM",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="fungi",
            name="smell",
            field=models.TextField(blank=True, null=True),
        ),
    ]
